apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: sre-job-processor
spec:
  replicas: 5
  selector:
    matchLabels:
      app: job-processor-worker
  template:
    metadata:
      labels:
        app: job-processor-worker
    spec:
      containers:
        - name: worker
          image: horlami228/sre-job-processor:latest
          command: ["python", "worker.py"]
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: sre-job-processor-secrets
                  key: DATABASE_URL
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: sre-job-processor-secrets
                  key: REDIS_URL
          livenessProbe:
            exec:
              command:
                - python
                - -c
                - |
                  import time, sys
                  t = float(open('/tmp/worker-alive').read())
                  sys.exit(0 if time.time() - t < 30 else 1)
            initialDelaySeconds: 10
            periodSeconds: 15
            failureThreshold: 3
