apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: sre-job-processor
spec:
  type: NodePort
  selector:
    app: job-processor-app
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30001
